import {
  BitcoinNetwork,
  ipcDataDir,
  jdsPort,
  monitoringPort,
  poolPort,
  workerHashrateExtension,
} from './utils'

export type PoolConfig = {
  authorityPublicKey: string
  authoritySecretKey: string
  coinbaseRewardAddress: string
  poolSignature: string
  network: BitcoinNetwork
  sharesPerMinute: number
  jdsEnabled: boolean
}

const tomlFloat = (n: number): string =>
  Number.isInteger(n) ? `${n}.0` : `${n}`

// JSON string escaping is a subset of TOML basic-string escaping.
const tomlString = (s: string): string => JSON.stringify(s)

export function generatePoolToml(c: PoolConfig): string {
  return `# Stratum V2 Pool configuration
# Generated by StartOS

authority_public_key = "${c.authorityPublicKey}"
authority_secret_key = "${c.authoritySecretKey}"
cert_validity_sec = 3600
listen_address = "0.0.0.0:${poolPort}"

coinbase_reward_script = ${tomlString(`addr(${c.coinbaseRewardAddress})`)}
server_id = 1
pool_signature = ${tomlString(c.poolSignature)}

shares_per_minute = ${tomlFloat(c.sharesPerMinute)}
share_batch_size = 10

supported_extensions = [${workerHashrateExtension}]
required_extensions = []

monitoring_address = "0.0.0.0:${monitoringPort}"
monitoring_cache_refresh_secs = 15

[template_provider_type.BitcoinCoreIpc]
version = 31
network = "${c.network}"
data_dir = "${ipcDataDir}"
fee_threshold = 100
min_interval = 5
${
  c.jdsEnabled
    ? `
[jds]
listen_address = "0.0.0.0:${jdsPort}"
`
    : ''
}`
}
