import { createHash } from 'crypto'
import { secp256k1 } from '@noble/curves/secp256k1.js'
import { createBase58check } from '@scure/base'

// Downstream listener that translators and JD clients connect to.
export const poolPort = 3333
export const poolHostId = 'pool'
export const poolInterfaceId = 'pool'

// Embedded Job Declaration Server, present only while it is enabled.
export const jdsPort = 3334
export const jdsHostId = 'jds'
export const jdsInterfaceId = 'jds'

// Read-only HTTP monitoring API.
export const monitoringPort = 9090
export const monitoringHostId = 'monitoring'

// SV2 extension 0x0002, Worker-Specific Hashrate Tracking.
export const workerHashrateExtension = '0x0002'

// Bitcoin's IPC directory, mounted read-only. It holds `bitcoin-core.sock`,
// but the pool resolves its socket as `${dataDir}/[network/]node.sock`, so
// ipcDataDir holds a symlink under that name rather than being the mount.
export const bitcoindIpcMount = '/mnt/bitcoind-ipc'
export const bitcoindSocketName = 'bitcoin-core.sock'
export const ipcDataDir = '/data/ipc'

export type BitcoinNetwork = 'mainnet' | 'testnet4' | 'signet' | 'regtest'

export function ipcSocketLink(network: BitcoinNetwork): string {
  return network === 'mainnet'
    ? `${ipcDataDir}/node.sock`
    : `${ipcDataDir}/${network}/node.sock`
}

// SRI's key encoding: base58check of the bare 32-byte secret, and of the
// x-only public key behind a little-endian u16 version 1.
const base58check = createBase58check((data: Uint8Array) =>
  createHash('sha256').update(data).digest(),
)

export function generateAuthorityKeypair() {
  const secret = secp256k1.utils.randomSecretKey()
  const versioned = new Uint8Array(34)
  versioned[0] = 1
  versioned.set(secp256k1.getPublicKey(secret, true).subarray(1), 2)
  return {
    secretKey: base58check.encode(secret),
    publicKey: base58check.encode(versioned),
  }
}

export function observePoolStdout(onReady: () => void) {
  const readyMessage =
    'Required template data received, ready to accept connections'
  let tail = ''
  return (chunk: Buffer | string) => {
    process.stdout.write(chunk)
    const text = tail + chunk.toString()
    if (text.includes(readyMessage)) onReady()
    tail = text.slice(-(readyMessage.length - 1))
  }
}

export type PoolConfig = {
  authorityPublicKey: string
  authoritySecretKey: string
  coinbaseRewardAddress: string
  poolSignature: string
  network: BitcoinNetwork
  sharesPerMinute: number
  maxPastJobs: number | null
  jdsEnabled: boolean
}

const tomlFloat = (n: number): string =>
  Number.isInteger(n) ? `${n}.0` : `${n}`

// JSON string escaping is a subset of TOML basic-string escaping.
const tomlString = (s: string): string => JSON.stringify(s)

export function generatePoolToml(c: PoolConfig): string {
  return `# Stratum V2 Pool configuration
# Generated by StartOS

authority_public_key = "${c.authorityPublicKey}"
authority_secret_key = "${c.authoritySecretKey}"
cert_validity_sec = 3600
listen_address = "0.0.0.0:${poolPort}"

coinbase_reward_script = ${tomlString(`addr(${c.coinbaseRewardAddress})`)}
server_id = 1
pool_signature = ${tomlString(c.poolSignature)}

shares_per_minute = ${tomlFloat(c.sharesPerMinute)}
share_batch_size = 10
${c.maxPastJobs === null ? '' : `max_past_jobs = ${c.maxPastJobs}\n`}
supported_extensions = [${workerHashrateExtension}]
required_extensions = []

monitoring_address = "0.0.0.0:${monitoringPort}"
monitoring_cache_refresh_secs = 15

[template_provider_type.BitcoinCoreIpc]
version = 31
network = "${c.network}"
data_dir = "${ipcDataDir}"
fee_threshold = 100
min_interval = 5
${
  c.jdsEnabled
    ? `
[jds]
listen_address = "0.0.0.0:${jdsPort}"
`
    : ''
}`
}
